plugins {
    id 'java'
    id 'maven-publish'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
    id 'com.gradleup.shadow' version '9.3.0'
}

version = project.version;

configurations {
    shadowBundle
    implementation.extendsFrom(shadowBundle)
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

repositories {
    mavenCentral()
    maven {
        name = "hytale-release"
        url = uri("https://maven.hytale.com/release")
    }
    maven {
        name = "Jitpack"
        url = uri("https://jitpack.io")
    }
    maven {
        name = "HelpChat"
        url = uri("https://repo.helpch.at/releases")
    }
}


def os = org.gradle.internal.os.OperatingSystem.current()
def userHome = System.getProperty("user.home")

def hytaleHome
def hytaleServerJar
if (os.isWindows()) {
    hytaleHome = "$userHome/AppData/Roaming/Hytale"
} else if (os.isMacOsX()) {
    hytaleHome = "$userHome/Library/Application Support/Hytale"
} else if (os.isLinux()) {
    hytaleHome = "$userHome/.local/share/Hytale"
    if (!file(hytaleHome).exists()) {
        hytaleHome = "$userHome/.var/app/com.hypixel.HytaleLauncher/data/Hytale"
    }
} else {
    throw new GradleException("Unsupported OS for Hytale")
}

hytaleServerJar = "$hytaleHome/install/$patchline/package/game/$game_build/Server/HytaleServer.jar"



dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation files(file(hytaleServerJar).exists() ? hytaleServerJar : "$projectDir/HytaleServer.jar")
    //implementation(files(System.getProperty("user.home") + "/AppData/Roaming/Hytale/install/release/package/game/$game_build/Server/HytaleServer.jar"))
    //implementation 'org.xerial:sqlite-jdbc:3.45.1.0'
    shadowBundle files('libs/codeclib-1.1.0.jar')
    shadowBundle 'org.slf4j:slf4j-simple:2.0.17'
    shadowBundle 'org.xerial:sqlite-jdbc:3.45.1.0'
    compileOnly 'net.luckperms:api:5.4'
    compileOnly 'at.helpch:placeholderapi-hytale:1.0.4'
    //runtimeOnly(files("./run/LuckPerms-Hytale-5.5.25-beta10.jar"))
}

test {
    useJUnitPlatform()
}

processResources {
    var expandProps = [
        'name'          : project.name,
        'version'       : project.version,
        'group'         : project.group,
        'description'   : mod_description,
        'website'       : website,
        'server_version': server_version,
        'entry_point'   : entry_point
    ]

    filesMatching(['manifest.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

def serverRunDir = file("$projectDir/run")

idea.project.settings.runConfigurations {
    'HytaleServer'(org.jetbrains.gradle.ext.Application) {
        mainClass = 'com.hypixel.hytale.Main'
        moduleName = project.idea.module.name + '.main'
        programParameters = "--allow-op --disable-sentry --assets=$hytaleHome/install/$patchline/package/game/latest/Assets.zip --mods=${file("src/main/").absolutePath}  --auth-mode=authenticated"
        workingDirectory = serverRunDir.absolutePath
    }
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
    configurations = [project.configurations.shadowBundle]
    relocate 'dev.unnm3d.codeclib', 'com.buuz135.simpleclaims.libs.codeclib'
    manifest {
        attributes(
                'Main-Class': 'com.buuz135.simpleclaims.Main'
        )
    }
}

tasks.build {
    dependsOn("shadowJar")
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    if (providers.environmentVariable("HT_MAVEN_USERNAME").present) {
        repositories {
            maven() {
                url = "https://maven.hytale-mods.dev/releases"
                credentials {
                    username = providers.environmentVariable("HT_MAVEN_USERNAME").get()
                    password = providers.environmentVariable("HT_MAVEN_PASSWORD").get()
                }
            }
        }
    }

}